Repository CS2103-AY1819S2-W13-4/main, pull requests merged in 2019-04, with the labels that each got.

#70 Allow multiple allergies to be added: Closes #66
  giatrosbook.json
  src/main/java/seedu/giatros/logic/commands/AddCommand.java
  src/main/java/seedu/giatros/logic/commands/AddallCommand.java
  src/main/java/seedu/giatros/logic/commands/EditCommand.java
  src/main/java/seedu/giatros/logic/parser/AddCommandParser.java
  src/main/java/seedu/giatros/logic/parser/AddallCommandParser.java
  src/main/java/seedu/giatros/logic/parser/EditCommandParser.java
  src/main/java/seedu/giatros/logic/parser/ParserUtil.java
  src/main/java/seedu/giatros/model/allergy/Allergy.java
  src/main/java/seedu/giatros/model/patient/Allergy.java
  src/main/java/seedu/giatros/model/patient/Patient.java
  src/main/java/seedu/giatros/model/tag/Tag.java
  src/main/java/seedu/giatros/model/util/SampleDataUtil.java
  src/main/java/seedu/giatros/storage/JsonAdaptedAllergy.java
  src/main/java/seedu/giatros/storage/JsonAdaptedPatient.java
  src/main/java/seedu/giatros/storage/JsonAdaptedTag.java
  src/main/java/seedu/giatros/ui/PatientCard.java
  src/test/data/JsonSerializableGiatrosBookTest/duplicatePatientGiatrosBook.json
  src/test/data/JsonSerializableGiatrosBookTest/typicalPatientsGiatrosBook.json
  src/test/java/guitests/guihandles/PatientCardHandle.java
  src/test/java/seedu/giatros/logic/LogicManagerTest.java
  src/test/java/seedu/giatros/logic/commands/AddallCommandTest.java
  src/test/java/seedu/giatros/logic/commands/CommandTestUtil.java
  src/test/java/seedu/giatros/logic/commands/EditCommandTest.java
  src/test/java/seedu/giatros/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/giatros/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/giatros/logic/parser/AddallCommandParserTest.java
  src/test/java/seedu/giatros/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/giatros/logic/parser/GiatrosBookParserTest.java
  src/test/java/seedu/giatros/logic/parser/ParserUtilTest.java
  src/test/java/seedu/giatros/model/GiatrosBookTest.java
  src/test/java/seedu/giatros/model/allergy/AllergyTest.java
  src/test/java/seedu/giatros/model/patient/AllergyTest.java
  src/test/java/seedu/giatros/model/patient/PatientTest.java
  src/test/java/seedu/giatros/model/patient/UniquePatientListTest.java
  src/test/java/seedu/giatros/model/tag/TagTest.java
  src/test/java/seedu/giatros/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/giatros/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/giatros/testutil/PatientBuilder.java
  src/test/java/seedu/giatros/testutil/PatientUtil.java
  src/test/java/seedu/giatros/testutil/TypicalPatients.java
  src/test/java/seedu/giatros/ui/PatientCardTest.java
  src/test/java/seedu/giatros/ui/PatientListPanelTest.java
  src/test/java/seedu/giatros/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.High, status.Ongoing, type.Enhancement

#73 Update the various documentations
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/DeletePersonSdForLogic.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SDforDeletePerson.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/giatros/MainApp.java
Labels: priority.High, type.Task

#75 Registering and login functionality added
  giatrosbook.json
  src/main/java/seedu/giatros/commons/core/EventsCenter.java
  src/main/java/seedu/giatros/commons/core/LogsCenter.java
  src/main/java/seedu/giatros/commons/core/session/UserSession.java
  src/main/java/seedu/giatros/commons/events/BaseEvent.java
  src/main/java/seedu/giatros/commons/events/storage/UpdateAccountEvent.java
  src/main/java/seedu/giatros/commons/events/ui/accounts/DisplayAccountListRequestEvent.java
  src/main/java/seedu/giatros/commons/events/ui/accounts/LoginEvent.java
  src/main/java/seedu/giatros/commons/events/ui/accounts/LogoutEvent.java
  src/main/java/seedu/giatros/commons/util/StringUtil.java
  src/main/java/seedu/giatros/logic/commands/account/LoginCommand.java
  src/main/java/seedu/giatros/logic/commands/account/LogoutCommand.java
  src/main/java/seedu/giatros/logic/commands/account/RegisterCommand.java
  src/main/java/seedu/giatros/logic/parser/CliSyntax.java
  src/main/java/seedu/giatros/logic/parser/GiatrosBookParser.java
  src/main/java/seedu/giatros/logic/parser/ParserUtil.java
  src/main/java/seedu/giatros/logic/parser/account/AccountParserUtil.java
  src/main/java/seedu/giatros/logic/parser/account/LoginCommandParser.java
  src/main/java/seedu/giatros/logic/parser/account/RegisterCommandParser.java
  src/main/java/seedu/giatros/model/GiatrosBook.java
  src/main/java/seedu/giatros/model/Model.java
  src/main/java/seedu/giatros/model/ModelManager.java
  src/main/java/seedu/giatros/model/ReadOnlyGiatrosBook.java
  src/main/java/seedu/giatros/model/VersionedGiatrosBook.java
  src/main/java/seedu/giatros/model/account/Account.java
  src/main/java/seedu/giatros/model/account/Name.java
  src/main/java/seedu/giatros/model/account/Password.java
  src/main/java/seedu/giatros/model/account/UniqueAccountList.java
  src/main/java/seedu/giatros/model/account/Username.java
  src/main/java/seedu/giatros/model/account/UsernameContainsKeywordPredicate.java
  src/main/java/seedu/giatros/model/account/exceptions/AccountException.java
  src/main/java/seedu/giatros/model/account/exceptions/AccountNotFoundException.java
  src/main/java/seedu/giatros/model/account/exceptions/DuplicateAccountException.java
  src/main/java/seedu/giatros/storage/JsonAdaptedAccount.java
  src/main/java/seedu/giatros/storage/JsonSerializableGiatrosBook.java
  src/main/java/seedu/giatros/ui/MainWindow.java
  src/main/java/seedu/giatros/ui/UiPart.java
  src/main/java/seedu/giatros/ui/account/AccountCard.java
  src/main/java/seedu/giatros/ui/account/AccountListPanel.java
  src/main/java/seedu/giatros/ui/account/UsernameDisplay.java
  src/main/resources/view/AccountListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UsernameDisplay.fxml
  src/test/java/seedu/giatros/logic/commands/AddCommandTest.java
  src/test/java/seedu/giatros/model/GiatrosBookTest.java
Labels: priority.Medium, severity.Low, status.Ongoing

#82 Updating the various documentations. Closes #76
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/wfxronald.adoc
Labels: priority.High, status.Ongoing, type.Task

#90 Refactoring addall and remall and other minor changes
  docs/UserGuide.adoc
  src/main/java/seedu/giatros/MainApp.java
  src/main/java/seedu/giatros/logic/commands/AddallCommand.java
  src/main/java/seedu/giatros/logic/commands/RemallCommand.java
  src/main/java/seedu/giatros/logic/parser/AddallCommandParser.java
  src/main/java/seedu/giatros/logic/parser/RemallCommandParser.java
  src/test/java/seedu/giatros/logic/commands/AddallCommandTest.java
  src/test/java/seedu/giatros/logic/commands/RemallCommandTest.java
  src/test/java/seedu/giatros/logic/parser/AddallCommandParserTest.java
  src/test/java/seedu/giatros/logic/parser/RemallCommandParserTest.java
Labels: priority.Medium, type.Task

#93 Updating developer guide and diagrams
  docs/images/SeEduLogo.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  docs/images/damithc.jpg
  docs/images/getting-started-ui-result-after.png
  docs/images/getting-started-ui-result-before.png
  docs/images/getting-started-ui-status-after.png
  docs/images/getting-started-ui-status-before.png
  docs/images/getting-started-ui-tag-after.png
  docs/images/getting-started-ui-tag-before.png
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
Labels: priority.High, type.Task
